-- 0004_seed_catalogue.sql
-- Reset the shopping data and seed 500 common Norwegian household items.
-- Run manually in the D1 console (there is no migration runner).
-- WARNING: this clears the existing shopping list and item catalogue.

DELETE FROM list_items;
DELETE FROM item_catalogue;

INSERT INTO item_catalogue (name, category) VALUES
  ('BANAN', 'frukt og grønt'),
  ('EPLE', 'frukt og grønt'),
  ('PÆRE', 'frukt og grønt'),
  ('APPELSIN', 'frukt og grønt'),
  ('KLEMENTIN', 'frukt og grønt'),
  ('MANDARIN', 'frukt og grønt'),
  ('SITRON', 'frukt og grønt'),
  ('LIME', 'frukt og grønt'),
  ('GRAPEFRUKT', 'frukt og grønt'),
  ('DRUER', 'frukt og grønt'),
  ('JORDBÆR', 'frukt og grønt'),
  ('BLÅBÆR', 'frukt og grønt'),
  ('BRINGEBÆR', 'frukt og grønt'),
  ('BJØRNEBÆR', 'frukt og grønt'),
  ('KIWI', 'frukt og grønt'),
  ('MANGO', 'frukt og grønt'),
  ('ANANAS', 'frukt og grønt'),
  ('MELON', 'frukt og grønt'),
  ('VANNMELON', 'frukt og grønt'),
  ('FERSKEN', 'frukt og grønt'),
  ('NEKTARIN', 'frukt og grønt'),
  ('PLOMME', 'frukt og grønt'),
  ('APRIKOS', 'frukt og grønt'),
  ('GRANATEPLE', 'frukt og grønt'),
  ('AVOKADO', 'frukt og grønt'),
  ('TOMAT', 'frukt og grønt'),
  ('CHERRYTOMAT', 'frukt og grønt'),
  ('AGURK', 'frukt og grønt'),
  ('SALAT', 'frukt og grønt'),
  ('ISBERGSALAT', 'frukt og grønt'),
  ('RUCCOLA', 'frukt og grønt'),
  ('SPINAT', 'frukt og grønt'),
  ('GRØNNKÅL', 'frukt og grønt'),
  ('BROKKOLI', 'frukt og grønt'),
  ('BLOMKÅL', 'frukt og grønt'),
  ('GULROT', 'frukt og grønt'),
  ('POTET', 'frukt og grønt'),
  ('SØTPOTET', 'frukt og grønt'),
  ('LØK', 'frukt og grønt'),
  ('RØDLØK', 'frukt og grønt'),
  ('HVITLØK', 'frukt og grønt'),
  ('PURRELØK', 'frukt og grønt'),
  ('VÅRLØK', 'frukt og grønt'),
  ('PAPRIKA', 'frukt og grønt'),
  ('CHILI', 'frukt og grønt'),
  ('SQUASH', 'frukt og grønt'),
  ('AUBERGINE', 'frukt og grønt'),
  ('MAIS', 'frukt og grønt'),
  ('SUKKERERTER', 'frukt og grønt'),
  ('SOPP', 'frukt og grønt'),
  ('CHAMPIGNON', 'frukt og grønt'),
  ('REDDIK', 'frukt og grønt'),
  ('RØDBETE', 'frukt og grønt'),
  ('KÅLROT', 'frukt og grønt'),
  ('STANGSELLERI', 'frukt og grønt'),
  ('ASPARGES', 'frukt og grønt'),
  ('ROSENKÅL', 'frukt og grønt'),
  ('HODEKÅL', 'frukt og grønt'),
  ('RØDKÅL', 'frukt og grønt'),
  ('KINAKÅL', 'frukt og grønt'),
  ('INGEFÆR', 'frukt og grønt'),
  ('PERSILLE', 'frukt og grønt'),
  ('BASILIKUM', 'frukt og grønt'),
  ('KORIANDER', 'frukt og grønt'),
  ('DILL', 'frukt og grønt'),
  ('GRESSLØK', 'frukt og grønt'),
  ('MYNTE', 'frukt og grønt'),
  ('RABARBRA', 'frukt og grønt'),
  ('PASJONSFRUKT', 'frukt og grønt'),
  ('KOKOSNØTT', 'frukt og grønt'),
  ('ERTER', 'frukt og grønt'),
  ('GROVBRØD', 'brød og bakevarer'),
  ('LOFF', 'brød og bakevarer'),
  ('RUNDSTYKKER', 'brød og bakevarer'),
  ('BAGUETTE', 'brød og bakevarer'),
  ('POLARBRØD', 'brød og bakevarer'),
  ('KNEKKEBRØD', 'brød og bakevarer'),
  ('PITA', 'brød og bakevarer'),
  ('TORTILLA', 'brød og bakevarer'),
  ('LEFSE', 'brød og bakevarer'),
  ('VAFLER', 'brød og bakevarer'),
  ('PANNEKAKER', 'brød og bakevarer'),
  ('CROISSANT', 'brød og bakevarer'),
  ('BOLLER', 'brød og bakevarer'),
  ('SKOLEBRØD', 'brød og bakevarer'),
  ('KANELBOLLER', 'brød og bakevarer'),
  ('MUFFINS', 'brød og bakevarer'),
  ('KAKE', 'brød og bakevarer'),
  ('SJOKOLADEKAKE', 'brød og bakevarer'),
  ('BRIOCHE', 'brød og bakevarer'),
  ('TOASTBRØD', 'brød og bakevarer'),
  ('FULLKORNSBRØD', 'brød og bakevarer'),
  ('SPELTBRØD', 'brød og bakevarer'),
  ('SURDEIGSBRØD', 'brød og bakevarer'),
  ('CIABATTA', 'brød og bakevarer'),
  ('FOCACCIA', 'brød og bakevarer'),
  ('NAANBRØD', 'brød og bakevarer'),
  ('HAMBURGERBRØD', 'brød og bakevarer'),
  ('HOTDOGBRØD', 'brød og bakevarer'),
  ('KAVRING', 'brød og bakevarer'),
  ('DONUT', 'brød og bakevarer'),
  ('MELK', 'Meieriprodukter'),
  ('LETTMELK', 'Meieriprodukter'),
  ('HELMELK', 'Meieriprodukter'),
  ('SKUMMET MELK', 'Meieriprodukter'),
  ('EKSTRA LETTMELK', 'Meieriprodukter'),
  ('LAKTOSEFRI MELK', 'Meieriprodukter'),
  ('FLØTE', 'Meieriprodukter'),
  ('KREMFLØTE', 'Meieriprodukter'),
  ('MATFLØTE', 'Meieriprodukter'),
  ('CRÈME FRAÎCHE', 'Meieriprodukter'),
  ('RØMME', 'Meieriprodukter'),
  ('LETTRØMME', 'Meieriprodukter'),
  ('SMØR', 'Meieriprodukter'),
  ('MARGARIN', 'Meieriprodukter'),
  ('BREMYKT', 'Meieriprodukter'),
  ('BRUNOST', 'Meieriprodukter'),
  ('HVITOST', 'Meieriprodukter'),
  ('NORVEGIA', 'Meieriprodukter'),
  ('JARLSBERG', 'Meieriprodukter'),
  ('GULOST', 'Meieriprodukter'),
  ('COTTAGE CHEESE', 'Meieriprodukter'),
  ('KREMOST', 'Meieriprodukter'),
  ('PHILADELPHIA', 'Meieriprodukter'),
  ('MOZZARELLA', 'Meieriprodukter'),
  ('PARMESAN', 'Meieriprodukter'),
  ('FETAOST', 'Meieriprodukter'),
  ('CHEDDAR', 'Meieriprodukter'),
  ('YOGHURT', 'Meieriprodukter'),
  ('NATURELL YOGHURT', 'Meieriprodukter'),
  ('GRESK YOGHURT', 'Meieriprodukter'),
  ('DRIKKEYOGHURT', 'Meieriprodukter'),
  ('SKYR', 'Meieriprodukter'),
  ('KEFIR', 'Meieriprodukter'),
  ('KVARG', 'Meieriprodukter'),
  ('VANILJESAUS', 'Meieriprodukter'),
  ('ISKREM', 'Meieriprodukter'),
  ('EGG', 'Meieriprodukter'),
  ('KJØTTDEIG', 'Kjøtt og fisk'),
  ('KARBONADEDEIG', 'Kjøtt og fisk'),
  ('SVINEKJØTT', 'Kjøtt og fisk'),
  ('STORFEKJØTT', 'Kjøtt og fisk'),
  ('KYLLING', 'Kjøtt og fisk'),
  ('KYLLINGFILET', 'Kjøtt og fisk'),
  ('KYLLINGLÅR', 'Kjøtt og fisk'),
  ('KYLLINGVINGER', 'Kjøtt og fisk'),
  ('KALKUN', 'Kjøtt og fisk'),
  ('BIFF', 'Kjøtt og fisk'),
  ('ENTRECÔTE', 'Kjøtt og fisk'),
  ('INDREFILET', 'Kjøtt og fisk'),
  ('YTREFILET', 'Kjøtt og fisk'),
  ('SVINEKOTELETTER', 'Kjøtt og fisk'),
  ('SVINEFILET', 'Kjøtt og fisk'),
  ('BACON', 'Kjøtt og fisk'),
  ('PØLSER', 'Kjøtt og fisk'),
  ('GRILLPØLSER', 'Kjøtt og fisk'),
  ('WIENERPØLSER', 'Kjøtt og fisk'),
  ('KJØTTBOLLER', 'Kjøtt og fisk'),
  ('MEDISTERKAKER', 'Kjøtt og fisk'),
  ('LAMMEKJØTT', 'Kjøtt og fisk'),
  ('LAMMELÅR', 'Kjøtt og fisk'),
  ('PINNEKJØTT', 'Kjøtt og fisk'),
  ('RIBBE', 'Kjøtt og fisk'),
  ('SPEKESKINKE', 'Kjøtt og fisk'),
  ('SALAMI', 'Kjøtt og fisk'),
  ('SERVELAT', 'Kjøtt og fisk'),
  ('LEVERPOSTEI', 'Kjøtt og fisk'),
  ('KOKT SKINKE', 'Kjøtt og fisk'),
  ('LAKS', 'Kjøtt og fisk'),
  ('RØKT LAKS', 'Kjøtt og fisk'),
  ('ØRRET', 'Kjøtt og fisk'),
  ('TORSK', 'Kjøtt og fisk'),
  ('SEI', 'Kjøtt og fisk'),
  ('HYSE', 'Kjøtt og fisk'),
  ('MAKRELL', 'Kjøtt og fisk'),
  ('SILD', 'Kjøtt og fisk'),
  ('TUNFISK', 'Kjøtt og fisk'),
  ('REKER', 'Kjøtt og fisk'),
  ('FISKEKAKER', 'Kjøtt og fisk'),
  ('FISKEBOLLER', 'Kjøtt og fisk'),
  ('FISKEPINNER', 'Kjøtt og fisk'),
  ('FISKEGRATENG', 'Kjøtt og fisk'),
  ('KRABBE', 'Kjøtt og fisk'),
  ('BLÅSKJELL', 'Kjøtt og fisk'),
  ('SCAMPI', 'Kjøtt og fisk'),
  ('SALT', 'ingredienser og krydder'),
  ('PEPPER', 'ingredienser og krydder'),
  ('SUKKER', 'ingredienser og krydder'),
  ('BRUNT SUKKER', 'ingredienser og krydder'),
  ('MELIS', 'ingredienser og krydder'),
  ('VANILJESUKKER', 'ingredienser og krydder'),
  ('HVETEMEL', 'ingredienser og krydder'),
  ('SAMMALT MEL', 'ingredienser og krydder'),
  ('MAIZENA', 'ingredienser og krydder'),
  ('BAKEPULVER', 'ingredienser og krydder'),
  ('NATRON', 'ingredienser og krydder'),
  ('GJÆR', 'ingredienser og krydder'),
  ('TØRRGJÆR', 'ingredienser og krydder'),
  ('OLIVENOLJE', 'ingredienser og krydder'),
  ('RAPSOLJE', 'ingredienser og krydder'),
  ('SOLSIKKEOLJE', 'ingredienser og krydder'),
  ('EDDIK', 'ingredienser og krydder'),
  ('BALSAMICO', 'ingredienser og krydder'),
  ('SOYASAUS', 'ingredienser og krydder'),
  ('KETCHUP', 'ingredienser og krydder'),
  ('SENNEP', 'ingredienser og krydder'),
  ('MAJONES', 'ingredienser og krydder'),
  ('REMULADE', 'ingredienser og krydder'),
  ('BULJONG', 'ingredienser og krydder'),
  ('BULJONGTERNING', 'ingredienser og krydder'),
  ('GRØNNSAKSBULJONG', 'ingredienser og krydder'),
  ('TOMATPURÉ', 'ingredienser og krydder'),
  ('HERMETISKE TOMATER', 'ingredienser og krydder'),
  ('KOKOSMELK', 'ingredienser og krydder'),
  ('HONNING', 'ingredienser og krydder'),
  ('SIRUP', 'ingredienser og krydder'),
  ('PEANØTTSMØR', 'ingredienser og krydder'),
  ('NUGATTI', 'ingredienser og krydder'),
  ('JORDBÆRSYLTETØY', 'ingredienser og krydder'),
  ('BRINGEBÆRSYLTETØY', 'ingredienser og krydder'),
  ('MARMELADE', 'ingredienser og krydder'),
  ('KARRI', 'ingredienser og krydder'),
  ('PAPRIKAKRYDDER', 'ingredienser og krydder'),
  ('CHILIPULVER', 'ingredienser og krydder'),
  ('KANEL', 'ingredienser og krydder'),
  ('KARDEMOMME', 'ingredienser og krydder'),
  ('MUSKAT', 'ingredienser og krydder'),
  ('GURKEMEIE', 'ingredienser og krydder'),
  ('SPISSKUMMEN', 'ingredienser og krydder'),
  ('OREGANO', 'ingredienser og krydder'),
  ('TIMIAN', 'ingredienser og krydder'),
  ('ROSMARIN', 'ingredienser og krydder'),
  ('LAURBÆRBLAD', 'ingredienser og krydder'),
  ('HVITLØKSPULVER', 'ingredienser og krydder'),
  ('TACOKRYDDER', 'ingredienser og krydder'),
  ('GRILLKRYDDER', 'ingredienser og krydder'),
  ('BAKEKAKAO', 'ingredienser og krydder'),
  ('SJOKOLADEBITER', 'ingredienser og krydder'),
  ('GELATIN', 'ingredienser og krydder'),
  ('VANILJEESSENS', 'ingredienser og krydder'),
  ('MANDLER', 'ingredienser og krydder'),
  ('VALNØTTER', 'ingredienser og krydder'),
  ('HASSELNØTTER', 'ingredienser og krydder'),
  ('CASHEWNØTTER', 'ingredienser og krydder'),
  ('PINJEKJERNER', 'ingredienser og krydder'),
  ('ROSINER', 'ingredienser og krydder'),
  ('SESAMFRØ', 'ingredienser og krydder'),
  ('SOLSIKKEFRØ', 'ingredienser og krydder'),
  ('GRESSKARKJERNER', 'ingredienser og krydder'),
  ('FOND', 'ingredienser og krydder'),
  ('GRANDIOSA', 'frysevarer og ferdigmåltid'),
  ('FROSSENPIZZA', 'frysevarer og ferdigmåltid'),
  ('LASAGNE', 'frysevarer og ferdigmåltid'),
  ('FROSNE GRØNNSAKER', 'frysevarer og ferdigmåltid'),
  ('FROSNE BÆR', 'frysevarer og ferdigmåltid'),
  ('FROSNE ERTER', 'frysevarer og ferdigmåltid'),
  ('POMMES FRITES', 'frysevarer og ferdigmåltid'),
  ('POTETBÅTER', 'frysevarer og ferdigmåltid'),
  ('LØKRINGER', 'frysevarer og ferdigmåltid'),
  ('FROSSEN FISK', 'frysevarer og ferdigmåltid'),
  ('VÅRRULLER', 'frysevarer og ferdigmåltid'),
  ('WOK GRØNNSAKER', 'frysevarer og ferdigmåltid'),
  ('FROSNE KJØTTBOLLER', 'frysevarer og ferdigmåltid'),
  ('FERDIGMIDDAG', 'frysevarer og ferdigmåltid'),
  ('PAI', 'frysevarer og ferdigmåltid'),
  ('SAFTIS', 'frysevarer og ferdigmåltid'),
  ('FROSSEN KYLLING', 'frysevarer og ferdigmåltid'),
  ('PIZZASNURRER', 'frysevarer og ferdigmåltid'),
  ('PANNEKAKER FROSNE', 'frysevarer og ferdigmåltid'),
  ('FROSSEN LAKS', 'frysevarer og ferdigmåltid'),
  ('FROSNE REKER', 'frysevarer og ferdigmåltid'),
  ('POTETLOMPER', 'frysevarer og ferdigmåltid'),
  ('SMOOTHIE FROSNE BÆR', 'frysevarer og ferdigmåltid'),
  ('ISKREM BOKS', 'frysevarer og ferdigmåltid'),
  ('FISKEPINNER FROSNE', 'frysevarer og ferdigmåltid'),
  ('FROSSEN PIZZA MINI', 'frysevarer og ferdigmåltid'),
  ('PØLSEDEIG', 'frysevarer og ferdigmåltid'),
  ('HAVREGRYN', 'Kornprodukter'),
  ('LETTKOKTE HAVREGRYN', 'Kornprodukter'),
  ('MÜSLI', 'Kornprodukter'),
  ('CORNFLAKES', 'Kornprodukter'),
  ('FROSTIES', 'Kornprodukter'),
  ('CHEERIOS', 'Kornprodukter'),
  ('HAVREFRAS', 'Kornprodukter'),
  ('WEETABIX', 'Kornprodukter'),
  ('PUFFET RIS', 'Kornprodukter'),
  ('RIS', 'Kornprodukter'),
  ('JASMINRIS', 'Kornprodukter'),
  ('BASMATIRIS', 'Kornprodukter'),
  ('RISGRØT', 'Kornprodukter'),
  ('GRØTRIS', 'Kornprodukter'),
  ('PASTA', 'Kornprodukter'),
  ('SPAGHETTI', 'Kornprodukter'),
  ('MAKARONI', 'Kornprodukter'),
  ('PENNE', 'Kornprodukter'),
  ('FUSILLI', 'Kornprodukter'),
  ('LASAGNEPLATER', 'Kornprodukter'),
  ('TAGLIATELLE', 'Kornprodukter'),
  ('COUSCOUS', 'Kornprodukter'),
  ('BULGUR', 'Kornprodukter'),
  ('QUINOA', 'Kornprodukter'),
  ('BYGGRYN', 'Kornprodukter'),
  ('RØDE LINSER', 'Kornprodukter'),
  ('KIKERTER', 'Kornprodukter'),
  ('SORTE BØNNER', 'Kornprodukter'),
  ('KIDNEYBØNNER', 'Kornprodukter'),
  ('POLENTA', 'Kornprodukter'),
  ('PANNEKAKEMIX', 'Kornprodukter'),
  ('VAFFELMIX', 'Kornprodukter'),
  ('LINSER', 'Kornprodukter'),
  ('POTETGULL', 'snacks og godteri'),
  ('OSTEPOP', 'snacks og godteri'),
  ('SALTSTENGER', 'snacks og godteri'),
  ('POPCORN', 'snacks og godteri'),
  ('NACHOS', 'snacks og godteri'),
  ('DIPP', 'snacks og godteri'),
  ('SALSA', 'snacks og godteri'),
  ('GUACAMOLE', 'snacks og godteri'),
  ('MELKESJOKOLADE', 'snacks og godteri'),
  ('MØRK SJOKOLADE', 'snacks og godteri'),
  ('KVIKK LUNSJ', 'snacks og godteri'),
  ('SMASH', 'snacks og godteri'),
  ('NON STOP', 'snacks og godteri'),
  ('TWIST', 'snacks og godteri'),
  ('SEIGMENN', 'snacks og godteri'),
  ('VINGUMMI', 'snacks og godteri'),
  ('LAKRIS', 'snacks og godteri'),
  ('PASTILLER', 'snacks og godteri'),
  ('TYGGEGUMMI', 'snacks og godteri'),
  ('DIGESTIVE', 'snacks og godteri'),
  ('MARIE KJEKS', 'snacks og godteri'),
  ('HAVREKJEKS', 'snacks og godteri'),
  ('SJOKOLADEKJEKS', 'snacks og godteri'),
  ('SNICKERS', 'snacks og godteri'),
  ('KIT KAT', 'snacks og godteri'),
  ('DAIM', 'snacks og godteri'),
  ('TOBLERONE', 'snacks og godteri'),
  ('SALTLAKRIS', 'snacks og godteri'),
  ('KJEKS', 'snacks og godteri'),
  ('CHIPS', 'snacks og godteri'),
  ('SJOKOLADE', 'snacks og godteri'),
  ('VANN', 'Drikkevarer'),
  ('KULLSYRET VANN', 'Drikkevarer'),
  ('MINERALVANN', 'Drikkevarer'),
  ('COLA', 'Drikkevarer'),
  ('COLA ZERO', 'Drikkevarer'),
  ('SPRITE', 'Drikkevarer'),
  ('FANTA', 'Drikkevarer'),
  ('SOLO', 'Drikkevarer'),
  ('URGE', 'Drikkevarer'),
  ('PEPSI', 'Drikkevarer'),
  ('EPLEJUICE', 'Drikkevarer'),
  ('APPELSINJUICE', 'Drikkevarer'),
  ('MULTIJUICE', 'Drikkevarer'),
  ('JUICE', 'Drikkevarer'),
  ('SAFT', 'Drikkevarer'),
  ('SOLBÆRSAFT', 'Drikkevarer'),
  ('EPLEMOST', 'Drikkevarer'),
  ('ISTE', 'Drikkevarer'),
  ('KAFFE', 'Drikkevarer'),
  ('FILTERKAFFE', 'Drikkevarer'),
  ('KAFFEKAPSLER', 'Drikkevarer'),
  ('ESPRESSO', 'Drikkevarer'),
  ('TE', 'Drikkevarer'),
  ('GRØNN TE', 'Drikkevarer'),
  ('SVART TE', 'Drikkevarer'),
  ('URTETE', 'Drikkevarer'),
  ('KAKAOPULVER', 'Drikkevarer'),
  ('ENERGIDRIKK', 'Drikkevarer'),
  ('RED BULL', 'Drikkevarer'),
  ('SMOOTHIE', 'Drikkevarer'),
  ('ØL', 'Drikkevarer'),
  ('VIN', 'Drikkevarer'),
  ('BRUS', 'Drikkevarer'),
  ('TOALETTPAPIR', 'Husholdning'),
  ('TØRKEPAPIR', 'Husholdning'),
  ('KJØKKENRULL', 'Husholdning'),
  ('SERVIETTER', 'Husholdning'),
  ('OPPVASKSÅPE', 'Husholdning'),
  ('OPPVASKMASKIN TABLETTER', 'Husholdning'),
  ('OPPVASKMASKINSALT', 'Husholdning'),
  ('VASKEMIDDEL', 'Husholdning'),
  ('TØYMYKNER', 'Husholdning'),
  ('FLEKKFJERNER', 'Husholdning'),
  ('KLORIN', 'Husholdning'),
  ('ALLRENGJØRING', 'Husholdning'),
  ('GLASSRENGJØRING', 'Husholdning'),
  ('TOALETTRENS', 'Husholdning'),
  ('BADERENGJØRING', 'Husholdning'),
  ('SKUREPULVER', 'Husholdning'),
  ('OPPVASKBØRSTE', 'Husholdning'),
  ('OPPVASKSVAMP', 'Husholdning'),
  ('KLUTER', 'Husholdning'),
  ('MIKROFIBERKLUT', 'Husholdning'),
  ('SØPPELSEKKER', 'Husholdning'),
  ('SØPPELPOSER', 'Husholdning'),
  ('FRYSEPOSER', 'Husholdning'),
  ('MATPAPIR', 'Husholdning'),
  ('ALUMINIUMSFOLIE', 'Husholdning'),
  ('PLASTFOLIE', 'Husholdning'),
  ('BAKEPAPIR', 'Husholdning'),
  ('LYSPÆRE', 'Husholdning'),
  ('BATTERIER', 'Husholdning'),
  ('STEARINLYS', 'Husholdning'),
  ('TELYS', 'Husholdning'),
  ('FYRSTIKKER', 'Husholdning'),
  ('GULVMOPP', 'Husholdning'),
  ('LUFTFRISKER', 'Husholdning'),
  ('VASKEPULVER', 'Husholdning'),
  ('SKYLLEMIDDEL', 'Husholdning'),
  ('GRØNNSÅPE', 'Husholdning'),
  ('TANNPIRKER', 'Husholdning'),
  ('TAPE', 'Husholdning'),
  ('KLESKLYPER', 'Husholdning'),
  ('ZIP POSER', 'Husholdning'),
  ('HÅNDSÅPE KJØKKEN', 'Husholdning'),
  ('STØVKLUTER', 'Husholdning'),
  ('VASKEKLUT', 'Husholdning'),
  ('BLEIER', 'Omsorg og Helse'),
  ('BLEIER STØRRELSE 4', 'Omsorg og Helse'),
  ('BLEIER STØRRELSE 5', 'Omsorg og Helse'),
  ('VÅTSERVIETTER', 'Omsorg og Helse'),
  ('BARNEMAT', 'Omsorg og Helse'),
  ('BARNEGRØT', 'Omsorg og Helse'),
  ('VELLING', 'Omsorg og Helse'),
  ('MORSMELKERSTATNING', 'Omsorg og Helse'),
  ('SMOKK', 'Omsorg og Helse'),
  ('TÅTEFLASKE', 'Omsorg og Helse'),
  ('BÆSJPOSER', 'Omsorg og Helse'),
  ('BABYOLJE', 'Omsorg og Helse'),
  ('BABYKREM', 'Omsorg og Helse'),
  ('VASELIN', 'Omsorg og Helse'),
  ('SOLKREM', 'Omsorg og Helse'),
  ('SOLKREM BARN', 'Omsorg og Helse'),
  ('MYGGSPRAY', 'Omsorg og Helse'),
  ('PLASTER', 'Omsorg og Helse'),
  ('BANDASJE', 'Omsorg og Helse'),
  ('SÅRSALVE', 'Omsorg og Helse'),
  ('ANTIBAC', 'Omsorg og Helse'),
  ('MUNNBIND', 'Omsorg og Helse'),
  ('PARACET', 'Omsorg og Helse'),
  ('IBUX', 'Omsorg og Helse'),
  ('PARACETAMOL BARN', 'Omsorg og Helse'),
  ('NESESPRAY', 'Omsorg og Helse'),
  ('HALSTABLETTER', 'Omsorg og Helse'),
  ('HOSTESAFT', 'Omsorg og Helse'),
  ('TERMOMETER', 'Omsorg og Helse'),
  ('BOMULLSPINNER', 'Omsorg og Helse'),
  ('TANNBØRSTE', 'Omsorg og Helse'),
  ('TANNBØRSTE BARN', 'Omsorg og Helse'),
  ('TANNKREM', 'Omsorg og Helse'),
  ('TANNKREM BARN', 'Omsorg og Helse'),
  ('TANNTRÅD', 'Omsorg og Helse'),
  ('MUNNSKYLL', 'Omsorg og Helse'),
  ('SJAMPO', 'Omsorg og Helse'),
  ('SJAMPO BARN', 'Omsorg og Helse'),
  ('BALSAM', 'Omsorg og Helse'),
  ('DUSJSÅPE', 'Omsorg og Helse'),
  ('HÅNDSÅPE', 'Omsorg og Helse'),
  ('DEODORANT', 'Omsorg og Helse'),
  ('BARBERSKUM', 'Omsorg og Helse'),
  ('BARBERBLADER', 'Omsorg og Helse'),
  ('BIND', 'Omsorg og Helse'),
  ('TAMPONGER', 'Omsorg og Helse'),
  ('TRUSEINNLEGG', 'Omsorg og Helse'),
  ('FUKTIGHETSKREM', 'Omsorg og Helse'),
  ('Q-TIPS', 'Omsorg og Helse'),
  ('VITAMINER', 'Omsorg og Helse'),
  ('TRAN', 'Omsorg og Helse'),
  ('MULTIVITAMIN BARN', 'Omsorg og Helse'),
  ('KATTEMAT', 'Dyreprodukter'),
  ('KATTEMAT VÅT', 'Dyreprodukter'),
  ('KATTEMAT TØRR', 'Dyreprodukter'),
  ('KATTESAND', 'Dyreprodukter'),
  ('KATTEGODTERI', 'Dyreprodukter'),
  ('HUNDEMAT', 'Dyreprodukter'),
  ('HUNDEMAT VÅT', 'Dyreprodukter'),
  ('HUNDEMAT TØRR', 'Dyreprodukter'),
  ('HUNDEGODTERI', 'Dyreprodukter'),
  ('TYGGEBEIN', 'Dyreprodukter'),
  ('FUGLEFRØ', 'Dyreprodukter'),
  ('FISKEFÔR', 'Dyreprodukter'),
  ('KANINMAT', 'Dyreprodukter'),
  ('DYRELEKER', 'Dyreprodukter'),
  ('BÆSJEPOSER HUND', 'Dyreprodukter'),
  ('GAVEPAPIR', 'Annet'),
  ('GAVEBÅND', 'Annet'),
  ('BURSDAGSLYS', 'Annet'),
  ('BALLONGER', 'Annet'),
  ('SERVIETTER FEST', 'Annet'),
  ('ENGANGSBESTIKK', 'Annet'),
  ('ENGANGSTALLERKEN', 'Annet'),
  ('PLASTKOPPER', 'Annet'),
  ('SUGERØR', 'Annet'),
  ('GRILLKULL', 'Annet'),
  ('TENNVÆSKE', 'Annet'),
  ('BLOMSTER', 'Annet'),
  ('POTTEPLANTE', 'Annet'),
  ('JORD', 'Annet'),
  ('FRØ', 'Annet');
