-- 0004_seed_catalogue.sql
-- Catalogue of common Norwegian household items. Re-runnable and
-- NON-destructive: it adds each item to EVERY list (CROSS JOIN lists) and
-- overwrites the category if that item already exists in the list (upsert).
-- It does NOT delete any existing shopping-list or catalogue rows.
-- Run manually in the D1 console (there is no migration runner).

WITH seed(name, category) AS (VALUES
  ('Banan', 'Frukt og grønt'),
  ('Eple', 'Frukt og grønt'),
  ('Pære', 'Frukt og grønt'),
  ('Appelsin', 'Frukt og grønt'),
  ('Klementin', 'Frukt og grønt'),
  ('Mandarin', 'Frukt og grønt'),
  ('Sitron', 'Frukt og grønt'),
  ('Lime', 'Frukt og grønt'),
  ('Grapefrukt', 'Frukt og grønt'),
  ('Druer', 'Frukt og grønt'),
  ('Jordbær', 'Frukt og grønt'),
  ('Blåbær', 'Frukt og grønt'),
  ('Bringebær', 'Frukt og grønt'),
  ('Bjørnebær', 'Frukt og grønt'),
  ('Kiwi', 'Frukt og grønt'),
  ('Mango', 'Frukt og grønt'),
  ('Ananas', 'Frukt og grønt'),
  ('Melon', 'Frukt og grønt'),
  ('Vannmelon', 'Frukt og grønt'),
  ('Fersken', 'Frukt og grønt'),
  ('Nektarin', 'Frukt og grønt'),
  ('Plomme', 'Frukt og grønt'),
  ('Aprikos', 'Frukt og grønt'),
  ('Granateple', 'Frukt og grønt'),
  ('Avokado', 'Frukt og grønt'),
  ('Tomat', 'Frukt og grønt'),
  ('Cherrytomat', 'Frukt og grønt'),
  ('Agurk', 'Frukt og grønt'),
  ('Salat', 'Frukt og grønt'),
  ('Isbergsalat', 'Frukt og grønt'),
  ('Ruccola', 'Frukt og grønt'),
  ('Spinat', 'Frukt og grønt'),
  ('Grønnkål', 'Frukt og grønt'),
  ('Brokkoli', 'Frukt og grønt'),
  ('Blomkål', 'Frukt og grønt'),
  ('Gulrot', 'Frukt og grønt'),
  ('Potet', 'Frukt og grønt'),
  ('Søtpotet', 'Frukt og grønt'),
  ('Løk', 'Frukt og grønt'),
  ('Rødløk', 'Frukt og grønt'),
  ('Hvitløk', 'Frukt og grønt'),
  ('Purreløk', 'Frukt og grønt'),
  ('Vårløk', 'Frukt og grønt'),
  ('Paprika', 'Frukt og grønt'),
  ('Chili', 'Frukt og grønt'),
  ('Squash', 'Frukt og grønt'),
  ('Aubergine', 'Frukt og grønt'),
  ('Mais', 'Frukt og grønt'),
  ('Sukkererter', 'Frukt og grønt'),
  ('Sopp', 'Frukt og grønt'),
  ('Champignon', 'Frukt og grønt'),
  ('Reddik', 'Frukt og grønt'),
  ('Rødbete', 'Frukt og grønt'),
  ('Kålrot', 'Frukt og grønt'),
  ('Stangselleri', 'Frukt og grønt'),
  ('Asparges', 'Frukt og grønt'),
  ('Rosenkål', 'Frukt og grønt'),
  ('Hodekål', 'Frukt og grønt'),
  ('Rødkål', 'Frukt og grønt'),
  ('Kinakål', 'Frukt og grønt'),
  ('Ingefær', 'Frukt og grønt'),
  ('Persille', 'Frukt og grønt'),
  ('Basilikum', 'Frukt og grønt'),
  ('Koriander', 'Frukt og grønt'),
  ('Dill', 'Frukt og grønt'),
  ('Gressløk', 'Frukt og grønt'),
  ('Mynte', 'Frukt og grønt'),
  ('Rabarbra', 'Frukt og grønt'),
  ('Pasjonsfrukt', 'Frukt og grønt'),
  ('Kokosnøtt', 'Frukt og grønt'),
  ('Erter', 'Frukt og grønt'),
  ('Grovbrød', 'Brød og bakevarer'),
  ('Loff', 'Brød og bakevarer'),
  ('Rundstykker', 'Brød og bakevarer'),
  ('Baguette', 'Brød og bakevarer'),
  ('Polarbrød', 'Brød og bakevarer'),
  ('Knekkebrød', 'Brød og bakevarer'),
  ('Pita', 'Brød og bakevarer'),
  ('Tortilla', 'Brød og bakevarer'),
  ('Lefse', 'Brød og bakevarer'),
  ('Vafler', 'Brød og bakevarer'),
  ('Pannekaker', 'Brød og bakevarer'),
  ('Croissant', 'Brød og bakevarer'),
  ('Boller', 'Brød og bakevarer'),
  ('Skolebrød', 'Brød og bakevarer'),
  ('Kanelboller', 'Brød og bakevarer'),
  ('Muffins', 'Brød og bakevarer'),
  ('Kake', 'Brød og bakevarer'),
  ('Sjokoladekake', 'Brød og bakevarer'),
  ('Brioche', 'Brød og bakevarer'),
  ('Toastbrød', 'Brød og bakevarer'),
  ('Fullkornsbrød', 'Brød og bakevarer'),
  ('Speltbrød', 'Brød og bakevarer'),
  ('Surdeigsbrød', 'Brød og bakevarer'),
  ('Ciabatta', 'Brød og bakevarer'),
  ('Focaccia', 'Brød og bakevarer'),
  ('Naanbrød', 'Brød og bakevarer'),
  ('Hamburgerbrød', 'Brød og bakevarer'),
  ('Hotdogbrød', 'Brød og bakevarer'),
  ('Kavring', 'Brød og bakevarer'),
  ('Donut', 'Brød og bakevarer'),
  ('Melk', 'Meieriprodukter'),
  ('Lettmelk', 'Meieriprodukter'),
  ('Helmelk', 'Meieriprodukter'),
  ('Skummet melk', 'Meieriprodukter'),
  ('Ekstra lettmelk', 'Meieriprodukter'),
  ('Laktosefri melk', 'Meieriprodukter'),
  ('Fløte', 'Meieriprodukter'),
  ('Kremfløte', 'Meieriprodukter'),
  ('Matfløte', 'Meieriprodukter'),
  ('Crème fraîche', 'Meieriprodukter'),
  ('Rømme', 'Meieriprodukter'),
  ('Lettrømme', 'Meieriprodukter'),
  ('Smør', 'Meieriprodukter'),
  ('Margarin', 'Meieriprodukter'),
  ('Bremykt', 'Meieriprodukter'),
  ('Brunost', 'Meieriprodukter'),
  ('Hvitost', 'Meieriprodukter'),
  ('Norvegia', 'Meieriprodukter'),
  ('Jarlsberg', 'Meieriprodukter'),
  ('Gulost', 'Meieriprodukter'),
  ('Cottage cheese', 'Meieriprodukter'),
  ('Kremost', 'Meieriprodukter'),
  ('Philadelphia', 'Meieriprodukter'),
  ('Mozzarella', 'Meieriprodukter'),
  ('Parmesan', 'Meieriprodukter'),
  ('Fetaost', 'Meieriprodukter'),
  ('Cheddar', 'Meieriprodukter'),
  ('Yoghurt', 'Meieriprodukter'),
  ('Naturell yoghurt', 'Meieriprodukter'),
  ('Gresk yoghurt', 'Meieriprodukter'),
  ('Drikkeyoghurt', 'Meieriprodukter'),
  ('Skyr', 'Meieriprodukter'),
  ('Kefir', 'Meieriprodukter'),
  ('Kvarg', 'Meieriprodukter'),
  ('Vaniljesaus', 'Meieriprodukter'),
  ('Iskrem', 'Meieriprodukter'),
  ('Egg', 'Meieriprodukter'),
  ('Kjøttdeig', 'Kjøtt og fisk'),
  ('Karbonadedeig', 'Kjøtt og fisk'),
  ('Svinekjøtt', 'Kjøtt og fisk'),
  ('Storfekjøtt', 'Kjøtt og fisk'),
  ('Kylling', 'Kjøtt og fisk'),
  ('Kyllingfilet', 'Kjøtt og fisk'),
  ('Kyllinglår', 'Kjøtt og fisk'),
  ('Kyllingvinger', 'Kjøtt og fisk'),
  ('Kalkun', 'Kjøtt og fisk'),
  ('Biff', 'Kjøtt og fisk'),
  ('Entrecôte', 'Kjøtt og fisk'),
  ('Indrefilet', 'Kjøtt og fisk'),
  ('Ytrefilet', 'Kjøtt og fisk'),
  ('Svinekoteletter', 'Kjøtt og fisk'),
  ('Svinefilet', 'Kjøtt og fisk'),
  ('Bacon', 'Kjøtt og fisk'),
  ('Pølser', 'Kjøtt og fisk'),
  ('Grillpølser', 'Kjøtt og fisk'),
  ('Wienerpølser', 'Kjøtt og fisk'),
  ('Kjøttboller', 'Kjøtt og fisk'),
  ('Medisterkaker', 'Kjøtt og fisk'),
  ('Lammekjøtt', 'Kjøtt og fisk'),
  ('Lammelår', 'Kjøtt og fisk'),
  ('Pinnekjøtt', 'Kjøtt og fisk'),
  ('Ribbe', 'Kjøtt og fisk'),
  ('Spekeskinke', 'Kjøtt og fisk'),
  ('Salami', 'Kjøtt og fisk'),
  ('Servelat', 'Kjøtt og fisk'),
  ('Leverpostei', 'Kjøtt og fisk'),
  ('Kokt skinke', 'Kjøtt og fisk'),
  ('Laks', 'Kjøtt og fisk'),
  ('Røkt laks', 'Kjøtt og fisk'),
  ('Ørret', 'Kjøtt og fisk'),
  ('Torsk', 'Kjøtt og fisk'),
  ('Sei', 'Kjøtt og fisk'),
  ('Hyse', 'Kjøtt og fisk'),
  ('Makrell', 'Kjøtt og fisk'),
  ('Sild', 'Kjøtt og fisk'),
  ('Tunfisk', 'Kjøtt og fisk'),
  ('Reker', 'Kjøtt og fisk'),
  ('Fiskekaker', 'Kjøtt og fisk'),
  ('Fiskeboller', 'Kjøtt og fisk'),
  ('Fiskepinner', 'Kjøtt og fisk'),
  ('Fiskegrateng', 'Kjøtt og fisk'),
  ('Krabbe', 'Kjøtt og fisk'),
  ('Blåskjell', 'Kjøtt og fisk'),
  ('Scampi', 'Kjøtt og fisk'),
  ('Salt', 'Ingredienser og krydder'),
  ('Pepper', 'Ingredienser og krydder'),
  ('Sukker', 'Ingredienser og krydder'),
  ('Brunt sukker', 'Ingredienser og krydder'),
  ('Melis', 'Ingredienser og krydder'),
  ('Vaniljesukker', 'Ingredienser og krydder'),
  ('Hvetemel', 'Ingredienser og krydder'),
  ('Sammalt mel', 'Ingredienser og krydder'),
  ('Maizena', 'Ingredienser og krydder'),
  ('Bakepulver', 'Ingredienser og krydder'),
  ('Natron', 'Ingredienser og krydder'),
  ('Gjær', 'Ingredienser og krydder'),
  ('Tørrgjær', 'Ingredienser og krydder'),
  ('Olivenolje', 'Ingredienser og krydder'),
  ('Rapsolje', 'Ingredienser og krydder'),
  ('Solsikkeolje', 'Ingredienser og krydder'),
  ('Eddik', 'Ingredienser og krydder'),
  ('Balsamico', 'Ingredienser og krydder'),
  ('Soyasaus', 'Ingredienser og krydder'),
  ('Ketchup', 'Ingredienser og krydder'),
  ('Sennep', 'Ingredienser og krydder'),
  ('Majones', 'Ingredienser og krydder'),
  ('Remulade', 'Ingredienser og krydder'),
  ('Buljong', 'Ingredienser og krydder'),
  ('Buljongterning', 'Ingredienser og krydder'),
  ('Grønnsaksbuljong', 'Ingredienser og krydder'),
  ('Tomatpuré', 'Ingredienser og krydder'),
  ('Hermetiske tomater', 'Ingredienser og krydder'),
  ('Kokosmelk', 'Ingredienser og krydder'),
  ('Honning', 'Ingredienser og krydder'),
  ('Sirup', 'Ingredienser og krydder'),
  ('Peanøttsmør', 'Ingredienser og krydder'),
  ('Nugatti', 'Ingredienser og krydder'),
  ('Jordbærsyltetøy', 'Ingredienser og krydder'),
  ('Bringebærsyltetøy', 'Ingredienser og krydder'),
  ('Marmelade', 'Ingredienser og krydder'),
  ('Karri', 'Ingredienser og krydder'),
  ('Paprikakrydder', 'Ingredienser og krydder'),
  ('Chilipulver', 'Ingredienser og krydder'),
  ('Kanel', 'Ingredienser og krydder'),
  ('Kardemomme', 'Ingredienser og krydder'),
  ('Muskat', 'Ingredienser og krydder'),
  ('Gurkemeie', 'Ingredienser og krydder'),
  ('Spisskummen', 'Ingredienser og krydder'),
  ('Oregano', 'Ingredienser og krydder'),
  ('Timian', 'Ingredienser og krydder'),
  ('Rosmarin', 'Ingredienser og krydder'),
  ('Laurbærblad', 'Ingredienser og krydder'),
  ('Hvitløkspulver', 'Ingredienser og krydder'),
  ('Tacokrydder', 'Ingredienser og krydder'),
  ('Grillkrydder', 'Ingredienser og krydder'),
  ('Bakekakao', 'Ingredienser og krydder'),
  ('Sjokoladebiter', 'Ingredienser og krydder'),
  ('Gelatin', 'Ingredienser og krydder'),
  ('Vaniljeessens', 'Ingredienser og krydder'),
  ('Mandler', 'Ingredienser og krydder'),
  ('Valnøtter', 'Ingredienser og krydder'),
  ('Hasselnøtter', 'Ingredienser og krydder'),
  ('Cashewnøtter', 'Ingredienser og krydder'),
  ('Pinjekjerner', 'Ingredienser og krydder'),
  ('Rosiner', 'Ingredienser og krydder'),
  ('Sesamfrø', 'Ingredienser og krydder'),
  ('Solsikkefrø', 'Ingredienser og krydder'),
  ('Gresskarkjerner', 'Ingredienser og krydder'),
  ('Fond', 'Ingredienser og krydder'),
  ('Grandiosa', 'Frysevarer og ferdigmåltid'),
  ('Frossenpizza', 'Frysevarer og ferdigmåltid'),
  ('Lasagne', 'Frysevarer og ferdigmåltid'),
  ('Frosne grønnsaker', 'Frysevarer og ferdigmåltid'),
  ('Frosne bær', 'Frysevarer og ferdigmåltid'),
  ('Frosne erter', 'Frysevarer og ferdigmåltid'),
  ('Pommes frites', 'Frysevarer og ferdigmåltid'),
  ('Potetbåter', 'Frysevarer og ferdigmåltid'),
  ('Løkringer', 'Frysevarer og ferdigmåltid'),
  ('Frossen fisk', 'Frysevarer og ferdigmåltid'),
  ('Vårruller', 'Frysevarer og ferdigmåltid'),
  ('Wok grønnsaker', 'Frysevarer og ferdigmåltid'),
  ('Frosne kjøttboller', 'Frysevarer og ferdigmåltid'),
  ('Ferdigmiddag', 'Frysevarer og ferdigmåltid'),
  ('Pai', 'Frysevarer og ferdigmåltid'),
  ('Saftis', 'Frysevarer og ferdigmåltid'),
  ('Frossen kylling', 'Frysevarer og ferdigmåltid'),
  ('Pizzasnurrer', 'Frysevarer og ferdigmåltid'),
  ('Pannekaker frosne', 'Frysevarer og ferdigmåltid'),
  ('Frossen laks', 'Frysevarer og ferdigmåltid'),
  ('Frosne reker', 'Frysevarer og ferdigmåltid'),
  ('Potetlomper', 'Frysevarer og ferdigmåltid'),
  ('Smoothie frosne bær', 'Frysevarer og ferdigmåltid'),
  ('Iskrem boks', 'Frysevarer og ferdigmåltid'),
  ('Fiskepinner frosne', 'Frysevarer og ferdigmåltid'),
  ('Frossen pizza mini', 'Frysevarer og ferdigmåltid'),
  ('Pølsedeig', 'Frysevarer og ferdigmåltid'),
  ('Havregryn', 'Kornprodukter'),
  ('Lettkokte havregryn', 'Kornprodukter'),
  ('Müsli', 'Kornprodukter'),
  ('Cornflakes', 'Kornprodukter'),
  ('Frosties', 'Kornprodukter'),
  ('Cheerios', 'Kornprodukter'),
  ('Havrefras', 'Kornprodukter'),
  ('Weetabix', 'Kornprodukter'),
  ('Puffet ris', 'Kornprodukter'),
  ('Ris', 'Kornprodukter'),
  ('Jasminris', 'Kornprodukter'),
  ('Basmatiris', 'Kornprodukter'),
  ('Risgrøt', 'Kornprodukter'),
  ('Grøtris', 'Kornprodukter'),
  ('Pasta', 'Kornprodukter'),
  ('Spaghetti', 'Kornprodukter'),
  ('Makaroni', 'Kornprodukter'),
  ('Penne', 'Kornprodukter'),
  ('Fusilli', 'Kornprodukter'),
  ('Lasagneplater', 'Kornprodukter'),
  ('Tagliatelle', 'Kornprodukter'),
  ('Couscous', 'Kornprodukter'),
  ('Bulgur', 'Kornprodukter'),
  ('Quinoa', 'Kornprodukter'),
  ('Byggryn', 'Kornprodukter'),
  ('Røde linser', 'Kornprodukter'),
  ('Kikerter', 'Kornprodukter'),
  ('Sorte bønner', 'Kornprodukter'),
  ('Kidneybønner', 'Kornprodukter'),
  ('Polenta', 'Kornprodukter'),
  ('Pannekakemix', 'Kornprodukter'),
  ('Vaffelmix', 'Kornprodukter'),
  ('Linser', 'Kornprodukter'),
  ('Potetgull', 'Snacks og godteri'),
  ('Ostepop', 'Snacks og godteri'),
  ('Saltstenger', 'Snacks og godteri'),
  ('Popcorn', 'Snacks og godteri'),
  ('Nachos', 'Snacks og godteri'),
  ('Dipp', 'Snacks og godteri'),
  ('Salsa', 'Snacks og godteri'),
  ('Guacamole', 'Snacks og godteri'),
  ('Melkesjokolade', 'Snacks og godteri'),
  ('Mørk sjokolade', 'Snacks og godteri'),
  ('Kvikk Lunsj', 'Snacks og godteri'),
  ('Smash', 'Snacks og godteri'),
  ('Non Stop', 'Snacks og godteri'),
  ('Twist', 'Snacks og godteri'),
  ('Seigmenn', 'Snacks og godteri'),
  ('Vingummi', 'Snacks og godteri'),
  ('Lakris', 'Snacks og godteri'),
  ('Pastiller', 'Snacks og godteri'),
  ('Tyggegummi', 'Snacks og godteri'),
  ('Digestive', 'Snacks og godteri'),
  ('Marie kjeks', 'Snacks og godteri'),
  ('Havrekjeks', 'Snacks og godteri'),
  ('Sjokoladekjeks', 'Snacks og godteri'),
  ('Snickers', 'Snacks og godteri'),
  ('Kit Kat', 'Snacks og godteri'),
  ('Daim', 'Snacks og godteri'),
  ('Toblerone', 'Snacks og godteri'),
  ('Saltlakris', 'Snacks og godteri'),
  ('Kjeks', 'Snacks og godteri'),
  ('Chips', 'Snacks og godteri'),
  ('Sjokolade', 'Snacks og godteri'),
  ('Vann', 'Drikkevarer'),
  ('Kullsyret vann', 'Drikkevarer'),
  ('Mineralvann', 'Drikkevarer'),
  ('Cola', 'Drikkevarer'),
  ('Cola Zero', 'Drikkevarer'),
  ('Sprite', 'Drikkevarer'),
  ('Fanta', 'Drikkevarer'),
  ('Solo', 'Drikkevarer'),
  ('Urge', 'Drikkevarer'),
  ('Pepsi', 'Drikkevarer'),
  ('Eplejuice', 'Drikkevarer'),
  ('Appelsinjuice', 'Drikkevarer'),
  ('Multijuice', 'Drikkevarer'),
  ('Juice', 'Drikkevarer'),
  ('Saft', 'Drikkevarer'),
  ('Solbærsaft', 'Drikkevarer'),
  ('Eplemost', 'Drikkevarer'),
  ('Iste', 'Drikkevarer'),
  ('Kaffe', 'Drikkevarer'),
  ('Filterkaffe', 'Drikkevarer'),
  ('Kaffekapsler', 'Drikkevarer'),
  ('Espresso', 'Drikkevarer'),
  ('Te', 'Drikkevarer'),
  ('Grønn te', 'Drikkevarer'),
  ('Svart te', 'Drikkevarer'),
  ('Urtete', 'Drikkevarer'),
  ('Kakaopulver', 'Drikkevarer'),
  ('Energidrikk', 'Drikkevarer'),
  ('Red Bull', 'Drikkevarer'),
  ('Smoothie', 'Drikkevarer'),
  ('Øl', 'Drikkevarer'),
  ('Vin', 'Drikkevarer'),
  ('Brus', 'Drikkevarer'),
  ('Toalettpapir', 'Husholdning'),
  ('Tørkepapir', 'Husholdning'),
  ('Kjøkkenrull', 'Husholdning'),
  ('Servietter', 'Husholdning'),
  ('Oppvasksåpe', 'Husholdning'),
  ('Oppvaskmaskin tabletter', 'Husholdning'),
  ('Oppvaskmaskinsalt', 'Husholdning'),
  ('Vaskemiddel', 'Husholdning'),
  ('Tøymykner', 'Husholdning'),
  ('Flekkfjerner', 'Husholdning'),
  ('Klorin', 'Husholdning'),
  ('Allrengjøring', 'Husholdning'),
  ('Glassrengjøring', 'Husholdning'),
  ('Toalettrens', 'Husholdning'),
  ('Baderengjøring', 'Husholdning'),
  ('Skurepulver', 'Husholdning'),
  ('Oppvaskbørste', 'Husholdning'),
  ('Oppvasksvamp', 'Husholdning'),
  ('Kluter', 'Husholdning'),
  ('Mikrofiberklut', 'Husholdning'),
  ('Søppelsekker', 'Husholdning'),
  ('Søppelposer', 'Husholdning'),
  ('Fryseposer', 'Husholdning'),
  ('Matpapir', 'Husholdning'),
  ('Aluminiumsfolie', 'Husholdning'),
  ('Plastfolie', 'Husholdning'),
  ('Bakepapir', 'Husholdning'),
  ('Lyspære', 'Husholdning'),
  ('Batterier', 'Husholdning'),
  ('Stearinlys', 'Husholdning'),
  ('Telys', 'Husholdning'),
  ('Fyrstikker', 'Husholdning'),
  ('Gulvmopp', 'Husholdning'),
  ('Luftfrisker', 'Husholdning'),
  ('Vaskepulver', 'Husholdning'),
  ('Skyllemiddel', 'Husholdning'),
  ('Grønnsåpe', 'Husholdning'),
  ('Tannpirker', 'Husholdning'),
  ('Tape', 'Husholdning'),
  ('Klesklyper', 'Husholdning'),
  ('Zip poser', 'Husholdning'),
  ('Håndsåpe kjøkken', 'Husholdning'),
  ('Støvkluter', 'Husholdning'),
  ('Vaskeklut', 'Husholdning'),
  ('Bleier', 'Omsorg og helse'),
  ('Bleier størrelse 4', 'Omsorg og helse'),
  ('Bleier størrelse 5', 'Omsorg og helse'),
  ('Våtservietter', 'Omsorg og helse'),
  ('Barnemat', 'Omsorg og helse'),
  ('Barnegrøt', 'Omsorg og helse'),
  ('Velling', 'Omsorg og helse'),
  ('Morsmelkerstatning', 'Omsorg og helse'),
  ('Smokk', 'Omsorg og helse'),
  ('Tåteflaske', 'Omsorg og helse'),
  ('Bæsjposer', 'Omsorg og helse'),
  ('Babyolje', 'Omsorg og helse'),
  ('Babykrem', 'Omsorg og helse'),
  ('Vaselin', 'Omsorg og helse'),
  ('Solkrem', 'Omsorg og helse'),
  ('Solkrem barn', 'Omsorg og helse'),
  ('Myggspray', 'Omsorg og helse'),
  ('Plaster', 'Omsorg og helse'),
  ('Bandasje', 'Omsorg og helse'),
  ('Sårsalve', 'Omsorg og helse'),
  ('Antibac', 'Omsorg og helse'),
  ('Munnbind', 'Omsorg og helse'),
  ('Paracet', 'Omsorg og helse'),
  ('Ibux', 'Omsorg og helse'),
  ('Paracetamol barn', 'Omsorg og helse'),
  ('Nesespray', 'Omsorg og helse'),
  ('Halstabletter', 'Omsorg og helse'),
  ('Hostesaft', 'Omsorg og helse'),
  ('Termometer', 'Omsorg og helse'),
  ('Bomullspinner', 'Omsorg og helse'),
  ('Tannbørste', 'Omsorg og helse'),
  ('Tannbørste barn', 'Omsorg og helse'),
  ('Tannkrem', 'Omsorg og helse'),
  ('Tannkrem barn', 'Omsorg og helse'),
  ('Tanntråd', 'Omsorg og helse'),
  ('Munnskyll', 'Omsorg og helse'),
  ('Sjampo', 'Omsorg og helse'),
  ('Sjampo barn', 'Omsorg og helse'),
  ('Balsam', 'Omsorg og helse'),
  ('Dusjsåpe', 'Omsorg og helse'),
  ('Håndsåpe', 'Omsorg og helse'),
  ('Deodorant', 'Omsorg og helse'),
  ('Barberskum', 'Omsorg og helse'),
  ('Barberblader', 'Omsorg og helse'),
  ('Bind', 'Omsorg og helse'),
  ('Tamponger', 'Omsorg og helse'),
  ('Truseinnlegg', 'Omsorg og helse'),
  ('Fuktighetskrem', 'Omsorg og helse'),
  ('Q-tips', 'Omsorg og helse'),
  ('Vitaminer', 'Omsorg og helse'),
  ('Tran', 'Omsorg og helse'),
  ('Multivitamin barn', 'Omsorg og helse'),
  ('Kattemat', 'Dyreprodukter'),
  ('Kattemat våt', 'Dyreprodukter'),
  ('Kattemat tørr', 'Dyreprodukter'),
  ('Kattesand', 'Dyreprodukter'),
  ('Kattegodteri', 'Dyreprodukter'),
  ('Hundemat', 'Dyreprodukter'),
  ('Hundemat våt', 'Dyreprodukter'),
  ('Hundemat tørr', 'Dyreprodukter'),
  ('Hundegodteri', 'Dyreprodukter'),
  ('Tyggebein', 'Dyreprodukter'),
  ('Fuglefrø', 'Dyreprodukter'),
  ('Fiskefôr', 'Dyreprodukter'),
  ('Kaninmat', 'Dyreprodukter'),
  ('Dyreleker', 'Dyreprodukter'),
  ('Bæsjeposer hund', 'Dyreprodukter'),
  ('Gavepapir', 'Annet'),
  ('Gavebånd', 'Annet'),
  ('Bursdagslys', 'Annet'),
  ('Ballonger', 'Annet'),
  ('Servietter fest', 'Annet'),
  ('Engangsbestikk', 'Annet'),
  ('Engangstallerken', 'Annet'),
  ('Plastkopper', 'Annet'),
  ('Sugerør', 'Annet'),
  ('Grillkull', 'Annet'),
  ('Tennvæske', 'Annet'),
  ('Blomster', 'Annet'),
  ('Potteplante', 'Annet'),
  ('Jord', 'Annet'),
  ('Frø', 'Annet'),
  -- Generic staples (catalogue previously had only specific variants)
  ('Brød', 'Brød og bakevarer'),
  ('Ost', 'Meieriprodukter'),
  ('Mel', 'Ingredienser og krydder'),
  ('Olje', 'Ingredienser og krydder'),
  ('Kjøtt', 'Kjøtt og fisk'),
  ('Fisk', 'Kjøtt og fisk'),
  ('Frukt', 'Frukt og grønt'),
  ('Grønnsaker', 'Frukt og grønt'),
  ('Frokostblanding', 'Kornprodukter'),
  ('Pålegg', 'Kjøtt og fisk')
)
INSERT INTO item_catalogue (name, category, list_id)
SELECT s.name, s.category, l.id
FROM seed s CROSS JOIN lists l
WHERE true
ON CONFLICT(list_id, name) DO UPDATE SET category = excluded.category;
