-- 0006_expand_catalogue.sql
-- Adds 200 additional common grocery/household items to every list's
-- item_catalogue. Same pattern as 0004: non-destructive, re-runnable
-- upsert via CROSS JOIN lists; overwrites category on conflict but never
-- deletes existing rows.
-- Run manually in the D1 console (there is no migration runner).

WITH seed(name, category) AS (VALUES
  ('Kirsebær', 'Frukt og grønt'),
  ('Søtkirsebær', 'Frukt og grønt'),
  ('Stikkelsbær', 'Frukt og grønt'),
  ('Tranebær', 'Frukt og grønt'),
  ('Fiken', 'Frukt og grønt'),
  ('Dadler', 'Frukt og grønt'),
  ('Litchi', 'Frukt og grønt'),
  ('Papaya', 'Frukt og grønt'),
  ('Physalis', 'Frukt og grønt'),
  ('Mirabelle', 'Frukt og grønt'),
  ('Kaki', 'Frukt og grønt'),
  ('Fennikel', 'Frukt og grønt'),
  ('Artisjokk', 'Frukt og grønt'),
  ('Pak choi', 'Frukt og grønt'),
  ('Mangold', 'Frukt og grønt'),
  ('Friséesalat', 'Frukt og grønt'),
  ('Romansalat', 'Frukt og grønt'),
  ('Vårsalat', 'Frukt og grønt'),
  ('Selleriknoll', 'Frukt og grønt'),
  ('Nepe', 'Frukt og grønt'),
  ('Estragon', 'Frukt og grønt'),
  ('Salvie', 'Frukt og grønt'),
  ('Karse', 'Frukt og grønt'),
  ('Sjalottløk', 'Frukt og grønt'),
  ('Rugbrød', 'Brød og bakevarer'),
  ('Flatbrød', 'Brød og bakevarer'),
  ('Lompe', 'Brød og bakevarer'),
  ('Grissini', 'Brød og bakevarer'),
  ('Bagel', 'Brød og bakevarer'),
  ('Müslibrød', 'Brød og bakevarer'),
  ('Solsikkebrød', 'Brød og bakevarer'),
  ('Steinbakt brød', 'Brød og bakevarer'),
  ('Lavkarbobrød', 'Brød og bakevarer'),
  ('Glutenfritt brød', 'Brød og bakevarer'),
  ('Wienerbrød', 'Brød og bakevarer'),
  ('Mascarpone', 'Meieriprodukter'),
  ('Ricotta', 'Meieriprodukter'),
  ('Halloumi', 'Meieriprodukter'),
  ('Geitost', 'Meieriprodukter'),
  ('Pultost', 'Meieriprodukter'),
  ('Havremelk', 'Meieriprodukter'),
  ('Mandelmelk', 'Meieriprodukter'),
  ('Soyamelk', 'Meieriprodukter'),
  ('Vegansk ost', 'Meieriprodukter'),
  ('Vegansk yoghurt', 'Meieriprodukter'),
  ('Vegansk rømme', 'Meieriprodukter'),
  ('Kalvekjøtt', 'Kjøtt og fisk'),
  ('Elgkjøtt', 'Kjøtt og fisk'),
  ('Reinsdyrkjøtt', 'Kjøtt og fisk'),
  ('Andebryst', 'Kjøtt og fisk'),
  ('Kanin', 'Kjøtt og fisk'),
  ('Geitekjøtt', 'Kjøtt og fisk'),
  ('Lammekoteletter', 'Kjøtt og fisk'),
  ('Chorizo', 'Kjøtt og fisk'),
  ('Pepperoni', 'Kjøtt og fisk'),
  ('Prosciutto', 'Kjøtt og fisk'),
  ('Parmaskinke', 'Kjøtt og fisk'),
  ('Kyllingpålegg', 'Kjøtt og fisk'),
  ('Kalkunpålegg', 'Kjøtt og fisk'),
  ('Makrell i tomat', 'Kjøtt og fisk'),
  ('Ansjos', 'Kjøtt og fisk'),
  ('Kaviar', 'Kjøtt og fisk'),
  ('Krabbeklør', 'Kjøtt og fisk'),
  ('Hummer', 'Kjøtt og fisk'),
  ('Østers', 'Kjøtt og fisk'),
  ('Pangasius', 'Kjøtt og fisk'),
  ('Steinbit', 'Kjøtt og fisk'),
  ('Breiflabb', 'Kjøtt og fisk'),
  ('Tofu', 'Kjøtt og fisk'),
  ('Tempeh', 'Kjøtt og fisk'),
  ('Vegankjøttdeig', 'Kjøtt og fisk'),
  ('Falafel', 'Kjøtt og fisk'),
  ('Cayennepepper', 'Ingredienser og krydder'),
  ('Chiliflak', 'Ingredienser og krydder'),
  ('Sambal Oelek', 'Ingredienser og krydder'),
  ('Sweet chili saus', 'Ingredienser og krydder'),
  ('BBQ saus', 'Ingredienser og krydder'),
  ('Pesto', 'Ingredienser og krydder'),
  ('Worcestershiresaus', 'Ingredienser og krydder'),
  ('Fiskesaus', 'Ingredienser og krydder'),
  ('Østerssaus', 'Ingredienser og krydder'),
  ('Hoisinsaus', 'Ingredienser og krydder'),
  ('Sriracha', 'Ingredienser og krydder'),
  ('Tabasco', 'Ingredienser og krydder'),
  ('Vaniljestang', 'Ingredienser og krydder'),
  ('Safran', 'Ingredienser og krydder'),
  ('Anis', 'Ingredienser og krydder'),
  ('Fennikelfrø', 'Ingredienser og krydder'),
  ('Korianderfrø', 'Ingredienser og krydder'),
  ('Sennepsfrø', 'Ingredienser og krydder'),
  ('Karvefrø', 'Ingredienser og krydder'),
  ('Stjerneanis', 'Ingredienser og krydder'),
  ('Nellik', 'Ingredienser og krydder'),
  ('Hvit pepper', 'Ingredienser og krydder'),
  ('Rødvinseddik', 'Ingredienser og krydder'),
  ('Hvitvinseddik', 'Ingredienser og krydder'),
  ('Kokosolje', 'Ingredienser og krydder'),
  ('Sesamolje', 'Ingredienser og krydder'),
  ('Agavesirup', 'Ingredienser og krydder'),
  ('Lønnesirup', 'Ingredienser og krydder'),
  ('Stevia', 'Ingredienser og krydder'),
  ('Mandelmel', 'Ingredienser og krydder'),
  ('Kokosmel', 'Ingredienser og krydder'),
  ('Hampfrø', 'Ingredienser og krydder'),
  ('Chiafrø', 'Ingredienser og krydder'),
  ('Linfrø', 'Ingredienser og krydder'),
  ('Peanøtter', 'Ingredienser og krydder'),
  ('Pistasjnøtter', 'Ingredienser og krydder'),
  ('Macadamianøtter', 'Ingredienser og krydder'),
  ('Tørkede aprikoser', 'Ingredienser og krydder'),
  ('Tørkede fiken', 'Ingredienser og krydder'),
  ('Tørkede dadler', 'Ingredienser og krydder'),
  ('Tørkede tranebær', 'Ingredienser og krydder'),
  ('Is på pinne', 'Frysevarer og ferdigmåltid'),
  ('Softis', 'Frysevarer og ferdigmåltid'),
  ('Frosne bønner', 'Frysevarer og ferdigmåltid'),
  ('Frossen blomkål', 'Frysevarer og ferdigmåltid'),
  ('Frossen brokkoli', 'Frysevarer og ferdigmåltid'),
  ('Iskake', 'Frysevarer og ferdigmåltid'),
  ('Frosne croissanter', 'Frysevarer og ferdigmåltid'),
  ('Frossen mango', 'Frysevarer og ferdigmåltid'),
  ('Havremel', 'Kornprodukter'),
  ('Bygg', 'Kornprodukter'),
  ('Spelt', 'Kornprodukter'),
  ('Rug', 'Kornprodukter'),
  ('Müslibarer', 'Kornprodukter'),
  ('Soyabønner', 'Kornprodukter'),
  ('Edamame', 'Kornprodukter'),
  ('Hirse', 'Kornprodukter'),
  ('Risnudler', 'Kornprodukter'),
  ('Eggnudler', 'Kornprodukter'),
  ('Glassnudler', 'Kornprodukter'),
  ('Udonnudler', 'Kornprodukter'),
  ('Ramen', 'Kornprodukter'),
  ('Twix', 'Snacks og godteri'),
  ('Mars', 'Snacks og godteri'),
  ('Bounty', 'Snacks og godteri'),
  ('Maltesers', 'Snacks og godteri'),
  ('Skumgodteri', 'Snacks og godteri'),
  ('Marshmallows', 'Snacks og godteri'),
  ('Lakrisrull', 'Snacks og godteri'),
  ('Smågodt', 'Snacks og godteri'),
  ('Proteinbar', 'Snacks og godteri'),
  ('Sportsdrikk', 'Drikkevarer'),
  ('Kombucha', 'Drikkevarer'),
  ('Iskaffe', 'Drikkevarer'),
  ('Most', 'Drikkevarer'),
  ('Druejuice', 'Drikkevarer'),
  ('Tranebærjuice', 'Drikkevarer'),
  ('Ananasjuice', 'Drikkevarer'),
  ('Mangojuice', 'Drikkevarer'),
  ('Sider', 'Drikkevarer'),
  ('Alkoholfritt øl', 'Drikkevarer'),
  ('Matboks', 'Husholdning'),
  ('Termos', 'Husholdning'),
  ('Drikkeflaske', 'Husholdning'),
  ('Avkalkningsmiddel', 'Husholdning'),
  ('Finvask', 'Husholdning'),
  ('Silikonform', 'Husholdning'),
  ('Bakeform', 'Husholdning'),
  ('Engangshansker', 'Husholdning'),
  ('Gummihansker', 'Husholdning'),
  ('Kost', 'Husholdning'),
  ('Feiebrett', 'Husholdning'),
  ('Vindusvisker', 'Husholdning'),
  ('Toalettbørste', 'Husholdning'),
  ('Møllmiddel', 'Husholdning'),
  ('Insektspray', 'Husholdning'),
  ('Sikringer', 'Husholdning'),
  ('Forlengerledning', 'Husholdning'),
  ('Vitamin D', 'Omsorg og helse'),
  ('Magnesium', 'Omsorg og helse'),
  ('Probiotika', 'Omsorg og helse'),
  ('Jerntilskudd', 'Omsorg og helse'),
  ('Allergitabletter', 'Omsorg og helse'),
  ('Øyedrops', 'Omsorg og helse'),
  ('Nesedrops', 'Omsorg og helse'),
  ('Kompresser', 'Omsorg og helse'),
  ('Sportstape', 'Omsorg og helse'),
  ('Kuldepose', 'Omsorg og helse'),
  ('Varmepute', 'Omsorg og helse'),
  ('Graviditetstest', 'Omsorg og helse'),
  ('Kondomer', 'Omsorg og helse'),
  ('Menstruasjonskopp', 'Omsorg og helse'),
  ('Intimvask', 'Omsorg og helse'),
  ('Rakekrem', 'Omsorg og helse'),
  ('Hårfjerningskrem', 'Omsorg og helse'),
  ('Hårspray', 'Omsorg og helse'),
  ('Hårgele', 'Omsorg og helse'),
  ('Leppepomade', 'Omsorg og helse'),
  ('Negleklipper', 'Omsorg og helse'),
  ('Pinsett', 'Omsorg og helse'),
  ('Hamstermat', 'Dyreprodukter'),
  ('Marsvinmat', 'Dyreprodukter'),
  ('Lim', 'Annet'),
  ('Saks', 'Annet'),
  ('Penn', 'Annet'),
  ('Notatbok', 'Annet'),
  ('Konvolutter', 'Annet'),
  ('Gjødsel', 'Annet')
)
INSERT INTO item_catalogue (name, category, list_id)
SELECT s.name, s.category, l.id
FROM seed s CROSS JOIN lists l
WHERE true
ON CONFLICT(list_id, name) DO UPDATE SET category = excluded.category;
